### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by Elise39u** [justinvandelaar/LaravelAvontuur#3]
foreach ($inventorySpace as $Space) {
               foreach ($Space->getInventoryItems as $value) {
                   if($value->item_id == $item_id->id) {
                       var_dump('Ik besta in de inventory');
                   } else {
                           $itemInventory = new inventory_item;
                           $itemInventory->inventory_id = $userid;
                           $itemInventory->item_id = $item_id->id;
                           $itemInventory->save();
                       }
                   }
                      }
                  }'

Vanwege deze code wordt de item alsnog ingevoerd op het moment dat je als volgt een inventory hebt
3->player_id  2->item_id 
3->player_id  5->item_id  //Add Extra item als ik op item pagina 2 ben
3->player_id  6->item_id //Add Extra item als ik op item pagina 2 ben

**Comment by justinvandelaar** [comment]
Dit is een Temp Oplossing Dit moet wel anders 
if ($value->item_id != $item_id->id) {
                           var_dump($value->item_id);
                       } else {
                           $itemInventory = new inventory_item;
                           $itemInventory->inventory_id = $userid;
                           $itemInventory->item_id = $item_id->id;
                           $itemInventory->save();
                       }

**Comment by Elise39u** [comment]
Update code ziet er nu zien uit
 foreach ($inventorySpace as $Space) {
                foreach ($Space->getInventoryItems as $value) {
                    if (in_array($value->item_id, (array) $item_id)) {
                        var_dump($value->item_id . ' Deze zit nog niet in de inventory');
                    } elseif($value->item_id != $item_id->id) {
                        var_dump($item_id->id . ' Is niet gelijk aan ' . $value->item_id);
                    }
                    else {
                        if ($value->item_id == $item_id->id) {
                            var_dump($item_id->id . ' Bestaat al in je inventory');
                        } else {
                            $itemInventory = new inventory_item;
                            $itemInventory->inventory_id = $userid;
                            $itemInventory->item_id = $item_id->id;
                            $itemInventory->save();
                        }
                    }
                }
            }
